[WIP] Mw 180/subscriptions list
IO2-2023-JB/team_10_frontend pull request #30
Opened 2023-04-21 01:06 UTC by nowakmikolaj

## Jira task

https://mojewideo.atlassian.net/jira/software/projects/MW/boards/1?selectedIssue=MW-180

## Description

Add subscriptions list on user's page

## Added/modified functionality

- user's page

## Screenshots

![image](https://user-images.githubusercontent.com/102852926/233516992-50ead1f4-a721-42b3-a9b2-c4d326a9c165.png)

## TO DO

Unsubscribing from subscriptions list - (problem with hooks)

2023-04-24 18:44 UTC, zagorskim requested changes
nie robilem review wcześniejszego brancha z subami więc trudno mi coś więcej tutaj powiedzieć, ale generalnie te katalogi w /pages - User i Video strasznie się rozrastają i może lepiej wydzielić suby na zewnątrz - komentarze też robiłem oddzielnie mimo, że są tylko pod video - może w takim razie jakiś subkatalog?

2023-04-24 18:44 UTC, zagorskim commented on src/pages/User/UserDetails.tsx
> +        ) : userDetails.userType == AccountType.Creator ? (
== -> ===

2023-04-24 18:44 UTC, zagorskim commented on src/pages/User/SubscriptionsListItem.tsx
> +        isSelf={loggedUserDetails?.id == userId}
== -> ===, generalnie podwójna równość zazwyczaj może być jedynie problemem, podwójna robi automatyczną konwersję jeżeli porównywane typy się nie zgadzają

2023-04-27 16:19 UTC, nowakmikolaj commented on src/pages/User/SubscriptionsListItem.tsx
> +        isSelf={loggedUserDetails?.id == userId}
done

2023-04-27 16:20 UTC, nowakmikolaj commented on src/pages/User/UserDetails.tsx
> +        ) : userDetails.userType == AccountType.Creator ? (
done

2023-04-28 13:43 UTC, nowakmikolaj commented
@zagorskim zrobiłem w końcu tak że po najechaniu myszką "Subskrybujesz" zmienia się na "Odsubskrybuj"

2023-04-28 13:50 UTC, zagorskim commented
> @zagorskim zrobiłem w końcu tak, że (wszędzie gdzie ten przycisk występuje) po najechaniu myszką "Subskrybujesz" zmienia się na "Odsubskrybuj"

Elegancko, jutro spojrzę

2023-04-29 11:55 UTC, zagorskim approved these changes

2023-04-29 11:56 UTC, zagorskim commented
Jest git, moim zdaniem możesz mergować

2023-04-30 19:32 UTC, nizioleque requested changes
ogolnie pieknie, masz pare komentarzy

wazna sprawa: najpierw zmerguj 181, potem zrob rebase tego (180) na dev, poniewaz na 181 zrobilem ten system zakladek z routingiem - on powinien byc tez zaimplementowany tutaj

2023-04-30 19:32 UTC, nizioleque commented on src/pages/Subscription/SubscribeButton.tsx
> +      onMouseOver={() => {
powinno być mouseLeave, nie mouseOver - zobacz sobie roznice (w tym przypadku to nie robi roznicy akurat, ale ogolnie mouseEnter jest "przeciwienstwem" mouseLeave a mouseOver to troche co innego)

2023-04-30 19:32 UTC, nizioleque commented on src/pages/Subscription/SubscriptionsListItem.tsx
> +    <ListItem key={userId}>
skoro podajesz key w SubscriptionsList to tutaj chyba nie jest potrzebny (no chyba ze dostajesz jakis blad jak go nie ma, to zostaw)

2023-04-30 19:32 UTC, nizioleque commented on src/pages/User/UserDetails.tsx
> +        ) : userDetails.userType === AccountType.Creator ? (
1. nie podobaja mi sie takie zagniezdzone ? : : : ...

zamiast tego mozesz zrobic 
```
{ warunek1 && <> ... </>}
{ warunek2 && <> ... </>}
```
itd.

2. jak chcesz nie wyswietlac nic to mozesz w komponencie zwrocic null (nie trzeba kombinowac z `<></>`, raczej nikt tak nie robi) - ale jak zrobisz punkt 1 to to nie bedzie juz potrzebne

2023-04-30 19:32 UTC, nizioleque commented on src/pages/Video/CreatorInfo.tsx
> +  width: string;
mozesz zrobic z tego opcjonalnego propa, wtedy nie bedzie trzeba robic tego przekazywania `auto` w `Metadata`

2023-05-01 10:31 UTC, nowakmikolaj commented on src/pages/Video/CreatorInfo.tsx
> +  width: string;
done

2023-05-01 10:34 UTC, nowakmikolaj commented on src/pages/Subscription/SubscribeButton.tsx
> +      onMouseOver={() => {
done

2023-05-01 10:40 UTC, nowakmikolaj commented on src/pages/User/UserDetails.tsx
> +        ) : userDetails.userType === AccountType.Creator ? (
done

2023-05-01 10:40 UTC, nowakmikolaj commented on src/pages/Subscription/SubscriptionsListItem.tsx
> +    <ListItem key={userId}>
done

2023-05-06 18:02 UTC, nizioleque approved these changes
pięknie mistrzu

2023-05-08 07:28 UTC, merged