MW-184 Add processing handling to Player
IO2-2023-JB/team_10_frontend pull request #34
Opened 2023-04-27 15:12 UTC by zagorskim

## Jira task

[[insert Jira task URL]
](https://mojewideo.atlassian.net/jira/software/projects/MW/boards/1?selectedIssue=MW-184)

## Description

Odczytywać stan przetworzenia filmu i pokazywać stosowny komunikat w playerze

## Added/modified functionality

- player processing view
- refactor player

## Screenshots

![image](https://user-images.githubusercontent.com/84161388/234906503-867c69e4-a7f8-45a1-b22d-fc45a7e4816c.png)

2023-05-06 18:43 UTC, nizioleque requested changes

2023-05-06 18:43 UTC, nizioleque commented on src/pages/Video/index.tsx
>          </>
te zewnętrzne `<> </>` nie są już potrzebne

2023-05-06 18:43 UTC, nizioleque commented on src/pages/Video/Player.tsx
> +  }, [processingNotification.status, queryClient, videoId]);
problem nr 1: częśc logiki odpowiedzialnej za pobieranie danych jest tutaj (to co zaznaczyłem), a część jest w `index.tsx` (tam jest pobieranie metadanych). To trochę nie po reactowemu - komponent-dziecko każe coś przeładować komponentowi rodzicowi. Według mnie lepiej by było całą logike pobierania przenieść do `index`, a ten komponent potraktować jako taki głupi kawałek UI bez żadnej logiki

2023-05-06 18:43 UTC, nizioleque commented on src/pages/Video/Player.tsx
> +  }, [processingNotification.status, queryClient, videoId]);
problem nr 2 (temat do dyskusji):
trochę to bez sensu, że w `videoNotificationState` co chwilę pobierasz te dane i równolegle każesz RQ pobierać te same dane. To pokazuje, że wykorzystnie effecta w recoilu było złym pomysłem

Myślę, że moglibyśmy rozwiązać problem poprzez pozbycie się tego effectu recoila (to co tam robisz jest trochę dziwne i przekomplikowane, po to mamy RQ żeby nam pomogło z takimi rzeczami). Czyli konkretnie widzę to tak:
- w recoilowym stanie `videoNotificationState` przechowywać tylko id filmu, który się wrzuca (lub `null` jeśli nic się nie wrzuca), usunąć effect recoila
- obecną logikę "przeładowywania" statusu filmu co chwilę (tę, która jest w effeccie recoila) przenieść do hooka, który wywołuje `useQuery` z odpowiednim `refetchInterval` i `enabled` (tzn. pobiera dane co X ms, tylko jeśli id filmu nie jest nullem, w `onSuccess` możesz zmienić ten stan na nulla jak film się pomyślnie wrzuci)
- tego hooka wywołać w `AppLayout` (a najlepiej zrobić oddzielny komponent np. `UploadStatusSnackbar`, który wstawisz w `AppLayout`). Dodatkowo, dzięki temu cała logika wyświetlania tego snackbara będzie w jednym miejscu, będzie można ją zrobić "po reactowemu", czytelniej zapisać (bez switchy w switchach)
- jak to zrobisz, to możesz wywalić to `invalidateQueries` - jeśli dobrze zrobisz `queryKey` w tym nowym hooku, to w `index.tsx` powinny zawsze być dostępne najnowsze dane (jeśli dobrze rozumiem jak działa RQ, to w jego pamięci dane są przypisane do klucza i jeśli wywołujesz `useQuery` w różnych miejscach z tym samym `queryKey` to odświeżenie danych w jednym miejscu powinno dostarczyć te nowe dane do wszystkich innych miejsc)
- dodatkowo, jak chcesz żeby metadane przeładowywały się co chwilę przy wszystkich filmach (nie tylko swoich własnych, tych które właśnie są wrzucane) to możesz dodać `refetchInterval` do hooka wywoływanego w `index.tsx`

nie narzucam tego, to propozycja, jak uważasz że to bez sensu to rozwiąż problem nr 1 i zostaw to jak jest

2023-05-15 23:26 UTC, zagorskim commented on src/pages/Video/Player.tsx
> +  }, [processingNotification.status, queryClient, videoId]);
możemy wyrzucić to do innego taska na sprint 5?

2023-05-16 17:07 UTC, nizioleque approved these changes

2023-05-16 17:07 UTC, nizioleque commented on src/pages/Video/Player.tsx
> +  }, [processingNotification.status, queryClient, videoId]);
to dodaj tego taska na sprint 5 i wtedy resolvuj

2023-05-17 00:26 UTC, zagorskim commented on src/pages/Video/Player.tsx
> +  }, [processingNotification.status, queryClient, videoId]);
leży w backlogu

2023-05-17 00:27 UTC, merged