MW-182/Drag&drop application
IO2-2023-JB/team_10_frontend pull request #35
Opened 2023-04-27 20:31 UTC by zagorskim

## Jira task

https://mojewideo.atlassian.net/jira/software/projects/MW/boards/1?selectedIssue=MW-182

## Description

Dodać nową kontrolkę uploadu do reszty formularzy, naprawić zachowanie dialogów po submicie

## Added/modified functionality

- zaimplementować drag&drop do dodawania avatarów, miniaturek i filmów

- dodać pole thumbnail przy edycji video metadata

- poprawić przy rejestracji i edycji profilu

- poprawić zamykanie się dialogów po submicie

## Screenshots

![image](https://user-images.githubusercontent.com/84161388/234983587-704f044d-6b78-4ab5-856e-66089c555a45.png)
![image](https://user-images.githubusercontent.com/84161388/234983621-629d190c-e643-4ee0-94c4-e3d141ffd283.png)
![image](https://user-images.githubusercontent.com/84161388/234983672-4c10a196-86a9-4355-b3b5-9e7bee57d676.png)
![image](https://user-images.githubusercontent.com/84161388/234983870-8df7b6b4-3c29-4d42-b4d7-92e875e7c99b.png)
![image](https://user-images.githubusercontent.com/84161388/234984006-7774b924-2bcf-4b3c-948c-f81ff83bb49a.png)

2023-05-06 17:56 UTC, nizioleque requested changes
no trochę bubel wyszedł, nie przetestowałeś ważnych scenariuszy (usuwanie obrazka i brak zmian przy edycji. Niech to będzie lekcja, że `!` w TS to bardzo niebezpieczny operator i trzeba go używać rozważnie, tylko w szczególnych uzasadnionych przypadkach

2023-05-15 23:48 UTC, zagorskim commented on src/components/formikFields/FormikFileUploader.tsx
> +    helpers.setValue(null);
pamiętam, że się psuło, ale nie pamiętam już dokładnie co to było
ogólnie kombinowałem z tym zdjęciem w initialValue, żeby przy edycji się wyświetlały i te zmiany to wymusiły

2023-05-15 23:57 UTC, zagorskim commented on src/components/formikFields/FormikFileUploader.tsx
> +                backgroundColor: 'primary.main',
czemuś to kiedyś służyło, ale jak teraz sprawdzam to nie mogę rozkminić - usuwam

2023-05-16 00:12 UTC, zagorskim commented on src/components/formikFields/FormikFileUploader.tsx
> +                marginRight: 2,
Wtedy przy schowanym Avatarze i Skeletonie mam przerwę z lewej i kontrolka nie jest zrównana z resztą inputów (chyba przez ten `<input/>`)

2023-05-16 01:26 UTC, zagorskim commented on src/components/formikFields/FormikFileUploader.tsx
> +                  ? `Aktualny ${label}`
odmiana przymiotników przez rodzaj zależnie od rzeczownika dodana w plikach adjectives.ts i nouns.ts xdddddd
twoje odmiany zmieniłem na numerals

2023-05-16 02:14 UTC, zagorskim commented on src/pages/User/UserDetailsEditForm.tsx
> +  const [areInitialValuesReady, setAreInitialValuesReady] = useState<boolean>();
nie pamiętam, dodałem z powrotem

2023-05-16 02:23 UTC, zagorskim commented on src/pages/User/UserDetailsEditForm.tsx
>      if (!shallowComparison(values, formikInitialValues)) {
dobrze wychwycone szefie

2023-05-16 03:05 UTC, zagorskim commented on src/pages/Video/MetadataForm.tsx
> +  const prepareInitialValues = useCallback(async () => {
Nowy hook znajduje się w src/utils/hooks.ts

btw, nie rozumiem tego ale wydaje mi się, że te pobieranie znacząco przyspieszyło z tym nowym rozwiązaniem

jak coś to jeszcze naprawiłem bug reprodukowany w poniższy sposób:
- zmieniasz miniaturkę
- zamyka się edycja
- bezpośrednio po powyższym ponownie otwierasz edycję
- do kontrolki drag&drop ładuje się stara wartość

2023-05-16 03:12 UTC, zagorskim commented on src/pages/Video/VideoDelete.tsx
> +  }, [isSuccess, navigate, queryClient]);
Zachowanie zależy od wartości flagi `asMenuItem`, oraz chcemy zamykać dialog za pomocą `setIsDeleteDialogOpen`, czyli używamy obiektów z bieżącego komponentu (w rejestracji tego nie ma) więc należałoby jakoś to przekazać; póki co nie wiem jak to zrobić (pierwszy pomysł to recoil) i nie wiem czy warto, bo kodu raczej przybędzie - może masz jakieś sprytne rozwiązanie na myśli?

2023-05-16 03:14 UTC, zagorskim commented on src/pages/Video/VideoDelete.tsx
> +  }, [isSuccess, navigate, queryClient]);
przy okazji naprawiłem tutaj wcześniej zauważony bug, który przekierowywał na homepage nawet jeżeli usuwaliśmy film za pomocą menu z tych trzech kropek, co nie powinno mieć miejsca moim zdaniem

2023-05-16 16:00 UTC, nizioleque commented on src/utils/adjectives.ts
> +}
```suggestion
type AdjectiveGenders = Record<AdjectiveGender, string>
```

2023-05-16 16:21 UTC, nizioleque commented on src/utils/adjectives.ts
> +}
to nie zadziała w przypadku słowa "samochód" (albo jakiegokolwiek innego męskiego nieosobowego) w liczbie mnogiej - wyjdzie "aktualni samochody". 

Proponuję w `NounGender` zamiast `Masculine` zrobić rozróżnienie na `MasculinePersonal` i `MasculineNonPersonal`

2023-05-16 16:35 UTC, nizioleque commented on src/pages/Register/RegisterForm.tsx
> +    if (values.avatarImage !== null)
a tutaj znowu są klamerki w `else`, a nie ma w `if`...

2023-05-16 18:34 UTC, zagorskim commented on src/pages/Register/RegisterForm.tsx
> +    if (values.avatarImage !== null)
nie robię tego bezmyślnie, ale moja filozofia jest bardzo prosta - jeżeli pod ifem lub elsem jest jeden statement to nie stawiam klamerek, jeżeli jest tam kilka linijek to pojawiają się w ramach jednego statementu wcięcie i na moje oko jest czytelnie, dla mnie wcięcia w tym przypadku rozwiązują problem 

ogólnie robię klamerkowanie na tyle zwięźle, na ile kompilator mi to przepuszcza i nie uważam tego za złe - możliwe, że znajdziesz gdzieś w moim kodzie łamanie tej zasady, ale wówczas była to nieuwaga

ogólnie preferuję jednolinijkowe bez klamerek i ZAWSZE w następnej linii - zawsze szukam logiki ifa POD ifem, a nie raz pod spodem, a raz z boku

jeżeli mocno ci na tym zależy to możemy zrobić po twojemu, ale dla mnie jest to niewygodne

2023-05-16 18:37 UTC, zagorskim commented on src/pages/Register/RegisterForm.tsx
>    };
słusznie, jakoś mi się na to nie wpadło

2023-05-16 18:42 UTC, zagorskim commented on src/pages/Video/MetadataForm.tsx
> +    const tags_processed = values.tags
2 dni w pythonie robią z człowieka troglodytę jak widać...

2023-05-16 18:52 UTC, zagorskim commented on src/pages/Video/MetadataForm.tsx
> +    } else
otóż mamy jeden statement po `else`, wcięcia zapewniają czytelność

2023-05-16 19:21 UTC, zagorskim commented on src/utils/numerals.ts
> +export enum Numeral {
fakt, zmieniłem na NumberDeclinedNoun, bo miałem kolizję z rzeczownikami, na podstawie których odmieniałem przymiotniki

2023-05-16 19:27 UTC, zagorskim commented on src/pages/Video/MetadataForm.tsx
> +    setThumbnailImage(values.thumbnail);
nie - to był bug, o którym pisałem wcześniej

2023-05-16 20:22 UTC, zagorskim commented on src/pages/Video/MetadataForm.tsx
> +  }, [areInitialValuesReady, prepareInitialValues]);
zrobione, ale chyba problem polegał na tym, żę w strict mode było to dwukrotnie wywoływane, jak sprawdzałem to jest callowane 2x i ref jest nadal potrzebny

2023-05-17 00:17 UTC, zagorskim commented
## Layout update

Miniaturki mają teraz przy uploadzie podgląd bardziej odpowiadający ich późniejszemu wyświetlaniu:

![image](https://github.com/IO2-2023-JB/team_10_frontend/assets/84161388/d00322cc-5018-4e3a-96c8-5b7768228beb)
![image](https://github.com/IO2-2023-JB/team_10_frontend/assets/84161388/728185c3-a7bf-42a2-af2f-7f6eb0910f67)

2023-05-17 21:35 UTC, nizioleque approved these changes
ostatnia drobnostka i mergujemyyy

2023-05-18 00:20 UTC, zagorskim commented on src/pages/Register/RegisterForm.tsx
> +      }
Fakt, ale 2 Boxy to kosztowało, chyba nie wymyślę nic zgrabniejszego (mógłbym podawać w propier style zamiast sx, ale to łamanie konwencji...
![image](https://github.com/IO2-2023-JB/team_10_frontend/assets/84161388/2a03c8fd-2852-4ac4-a1e0-2e62d1394185)

2023-05-18 00:58 UTC, merged