Mw 202/search
IO2-2023-JB/team_10_frontend pull request #41
Opened 2023-05-13 13:24 UTC by nizioleque

## Jira task

[insert Jira task URL]

## Description

[provide short description]

## Added/modified functionality

- [item 1]

## Screenshots

[paste screenshots]

2023-05-13 13:24 UTC, nizioleque commented
merge #38 first!

2023-05-18 20:29 UTC, zagorskim commented on src/api/search.ts
> +      return data;
```suggestion
      return (await axios.get('search', {
        params,
      })).data;
```

2023-05-18 22:58 UTC, zagorskim requested changes
Kurde fajnie to zakodzone, nie rozumiem działania niektórych komponentów, ale ufam, że tam wszystko elegancko jak w dokumentacji.

2023-05-18 22:58 UTC, zagorskim commented on src/components/NavBar/SearchField/SearchSuggestionWrapper.tsx
> +        componentProps.onClick?.(event);
Może handler do deklaracji w komponencie?

2023-05-18 22:58 UTC, zagorskim commented on src/components/NavBar/SearchField/SearchField.tsx
> +  }));
Nie wrzucamy takich funkcji do `utils.ts`?

2023-05-18 22:58 UTC, zagorskim commented on src/components/NavBar/SearchField/SearchField.tsx
> +      filterOptions={(x) => x}
To cokolwiek robi? Jak usuwam to nie widzę różnicy w sumie.

2023-05-18 22:58 UTC, zagorskim commented on src/components/NavBar/SearchField/SearchInput.tsx
> +          backgroundColor: 'rgba(255, 255, 255, 0.09)',
Kolor może do paletki w theme wrzucić?

2023-05-18 22:58 UTC, zagorskim commented on src/components/video/VideoListItem.tsx
> +            {isAuthor && [
Jak działają te kwadratowe nawiasy?

2023-05-18 22:58 UTC, zagorskim commented on src/components/video/VideoThumbnail.tsx
> +      {videoMetadata.duration !== null && !hideDuration && (
Czy gdziekolwiek aktualnie wykorzystujemy te pokazywanie długości? Nie mogę znaleźć.

2023-05-18 23:13 UTC, nizioleque commented on src/api/search.ts
> +      return data;
czemu?

kiedys juz o tym gadalismy, ja to widze tak:
domyślnie, w funkcjach, robimy tak jak ja zrobilem

tak jak ty zrobiles to wyjatek, jak nie robimy funkcji, tzn zeby uniknac czegos takiego:
```
queryFn: () => {
    const { data } = axios.get(...)
    return data
}
```
zamiast czegos takiego
```
queryFn: async () => (await axios.get(...)).data
```

2023-05-18 23:14 UTC, nizioleque commented on src/api/search.ts
> +      return data;
albo w sumie to obojetne, rzeczywiscie krocej jest, niech bedzie, chce spac

2023-05-18 23:15 UTC, nizioleque commented on src/api/search.ts
> +      return data;
dobra wycofuje sie, jak zmienilem to prettier mi to sformatowal tak:
```
      return (
        await axios.get('search', {
          params,
        })
      ).data;
```

czyli 5 linii, a moje ma 4. Zostawiam

2023-05-18 23:16 UTC, nizioleque commented on src/components/NavBar/SearchField/SearchField.tsx
> +      filterOptions={(x) => x}
tak, bez tego nie działa - podpowiedzi czasem w ogóle się nie pokazuję, niektóre są pomijane.
Dowód: https://mui.com/material-ui/react-autocomplete/#search-as-you-type
(Additionally, you will need to disable the built-in filtering...)

2023-05-18 23:16 UTC, nizioleque commented on src/components/NavBar/SearchField/SearchField.tsx
> +  }));
nie widzę potrzeby, bo ona służy konkretnie temu komponentowi, nigdy nie zostanie wykorzystana nigdzie indziej

2023-05-18 23:21 UTC, nizioleque commented on src/components/NavBar/SearchField/SearchSuggestionWrapper.tsx
> +        componentProps.onClick?.(event);
done

2023-05-18 23:36 UTC, nizioleque commented on src/components/NavBar/SearchField/SearchField.tsx
trudne się wylosowało

2023-05-18 23:51 UTC, nizioleque commented on src/components/NavBar/SearchField/SearchField.tsx
ale się udało

2023-05-18 23:53 UTC, nizioleque commented on src/components/NavBar/SearchField/SearchInput.tsx
> +          backgroundColor: 'rgba(255, 255, 255, 0.09)',
done

2023-05-18 23:54 UTC, nizioleque commented on src/components/video/VideoListItem.tsx
> +            {isAuthor && [
bez tego był error, że `Menu` przyjmuje tablicę a nie `React.Fragment`. To po prostu zwraca tablicę dwóch elementów, bo `Menu` jest takie dziwne że tak sobie życzy (i dlatego muszą mieć `key`, bo są wewnątrz tablicy)

2023-05-18 23:55 UTC, nizioleque commented on src/components/video/VideoThumbnail.tsx
> +      {videoMetadata.duration !== null && !hideDuration && (
powinno być wszędzie poza sugestiami (i filmami w trakcie przetwarzania), ale na backendzie się robi jeszcze (Saj)

2023-05-19 00:01 UTC, nizioleque commented on src/components/video/VideoThumbnail.tsx
> +      {videoMetadata.duration !== null && !hideDuration && (
jest na masterze na backendzie, źle co prawda, ale jest

2023-05-19 01:39 UTC, zagorskim approved these changes
giiit

2023-05-19 07:19 UTC, merged