Mw 204/search results
IO2-2023-JB/team_10_frontend pull request #42
Opened 2023-05-15 06:32 UTC by nowakmikolaj

## Jira task

[insert Jira task URL]

## Description

[provide short description]

## Added/modified functionality

- [item 1]

## Screenshots

[paste screenshots]

2023-05-16 17:09 UTC, nizioleque commented
merge MW-202 (#41) first

2023-05-17 23:38 UTC, nizioleque requested changes
Dobra robota mistrzu, te uwagi to same głupotki, szybko poprawisz

2023-05-17 23:38 UTC, nizioleque commented on src/types/SearchTypes.ts
> +export function GetSearchParams(params: URLSearchParams): SearchParams {
nazwa funkcji małą literką, to nie C#

2023-05-17 23:38 UTC, nizioleque commented on src/pages/Search/SearchPage.tsx
> +  const header = `Wyniki wyszukiwania "${params.get(SEARCH_PARAMS.QUERY)}":`;
usunąłbym ten dwukropek na końcu, a zamiast cudzysłowów możesz spróbować np pogrubić ten fragment

ale to już kwestia gustu, nie narzucam

2023-05-17 23:38 UTC, nizioleque commented on src/pages/Search/SearchPage.tsx
> +                  element: <VideoFiltersList videos={searchResults?.videos} />,
`?.` nie jest konieczne

2023-05-17 23:38 UTC, nizioleque commented on src/pages/User/Subscriptions/SubscriptionsList.tsx
> +        <UsersListItem key={sub.id} userId={sub.id} />
skąd ta zmiana nazwy?

2023-05-17 23:38 UTC, nizioleque commented on src/types/SearchTypes.ts
> +}
czemu jednocześnie używasz `?` i `null`? kiedy to jest `undefined` a kiedy `null`?

2023-05-17 23:38 UTC, nizioleque commented on src/pages/Search/SearchFilters.tsx
> +      });
obecnie jak zmienisz filtr to przycisk cofania cofa do poprzednich filtrów i każda zmiana filtrów dodaje się do historii. Fix:
```suggestion
      navigate({
        pathname: ROUTES.SEARCH,
        search: removeEmptySearchParams(searchParams).toString(),
      }, {replace: true});
```

2023-05-17 23:38 UTC, nizioleque commented on src/components/NavBar/SearchField/SearchField.tsx
> +  };
dodaj ifa zeby nie dalo sie szukac pustego stringa

2023-05-17 23:38 UTC, nizioleque commented on src/pages/Search/SearchPage.tsx
> +          {searchResults && (
mamy aktualnie taki problem, że jak zmieniasz jakiś filtr, to od nowa pobierają się wyniki i przez chwilę znowu widać kółeczko - to by było ok, gdyby na stronie były taby, filtry i kółeczko, ale obecnie na czas tego ładowania znikają i taby i filtry.

Proponuję takiego fixa: usunąć to renderowanie warunkowe (czyli `TabRouter` ma być zawsze wyrenderowany), a żeby uniknąć problemów z undefined, zrobić `searchResults?.videos ?? []` (analogicznie dla users i playlists)

powinno zadziałać

2023-05-18 20:15 UTC, nowakmikolaj commented on src/types/SearchTypes.ts
> +}
`undefined` musi być bo nie wszystkie parametry są jednoczenie w query (SearchField.tsx L44) 
`null` jest dlatego że przy odczytywaniu parametrów z url (L46 tutaj) `URLSearchParams.get()` zwraca string | null

2023-05-18 20:28 UTC, nowakmikolaj commented on src/types/SearchTypes.ts
> +export function GetSearchParams(params: URLSearchParams): SearchParams {
done

2023-05-18 20:52 UTC, nowakmikolaj commented on src/pages/Search/SearchPage.tsx
> +  const header = `Wyniki wyszukiwania "${params.get(SEARCH_PARAMS.QUERY)}":`;
racja będzie ładniej

2023-05-18 20:54 UTC, nowakmikolaj commented on src/pages/Search/SearchFilters.tsx
> +      });
done

2023-05-18 20:54 UTC, nowakmikolaj commented on src/pages/Search/SearchFilters.tsx
> +        />
done

2023-05-18 21:00 UTC, nowakmikolaj commented on src/api/search.ts
> +    enabled: searchParams.query != null && searchParams.query.length > 0,
1. pusty string to przeciez sprawdzam `length`
2. fakt

2023-05-18 21:06 UTC, nowakmikolaj commented on src/components/NavBar/SearchField/SearchField.tsx
> +  };
done

2023-05-19 06:39 UTC, nowakmikolaj commented on src/api/search.ts
> +    ? SortingTypes[searchParams.sortBy as keyof typeof SortingTypes]
done

2023-05-19 06:40 UTC, nowakmikolaj commented on src/components/NavBar/NavBar.tsx
> +  const query = new URLSearchParams(location.search).get(SEARCH_PARAMS.QUERY);
done

2023-05-19 06:41 UTC, nowakmikolaj commented on src/components/TabRouter.tsx
> +      <Tabs value={currentTab + query} sx={{ marginBottom: 2 }}>
done

2023-05-19 06:41 UTC, nowakmikolaj commented on src/pages/Search/SearchPage.tsx
> +                  element: <VideoFiltersList videos={searchResults?.videos} />,
donr

2023-05-19 06:42 UTC, nowakmikolaj commented on src/pages/User/Subscriptions/SubscriptionsList.tsx
> +        <UsersListItem key={sub.id} userId={sub.id} />
bo można tego użyć nie tylko do listy subów ale do listy użytkowników ogółem

2023-05-19 06:46 UTC, nowakmikolaj commented on src/pages/Search/SearchPage.tsx
> +          {searchResults && (
done

2023-05-19 08:17 UTC, nizioleque commented on src/types/SearchTypes.ts
> +}
tak jak gadaliśmy, niech zostanie

2023-05-19 08:50 UTC, merged