Mw 200/donates
IO2-2023-JB/team_10_frontend pull request #44
Opened 2023-05-17 18:28 UTC by nowakmikolaj

## Jira task

https://mojewideo.atlassian.net/jira/software/projects/MW/boards/1?selectedIssue=MW-200

## Description

1. wysylanie donejtów
- przycisk do donejtowania obok przycisku do subowania (wszędzie gdzie występuje)
- po nacisnieciu na przycisk otwiera sie dialog z polem na kwote do wpisania

2. wyplacanie:
- przycisk obok przycisku do edycji profilu, czyli tylko na stronie usera
- otwiera się dialog z polem na kwote do wypłacenia

## Added/modified functionality

- strona usera
- komponent UserInfo występujący pod filmami i na listach użytkowników

## Screenshots
![image](https://github.com/IO2-2023-JB/team_10_frontend/assets/102852926/15fb49f2-aa97-4d6f-8e7a-4ee0b94d0045)
![image](https://github.com/IO2-2023-JB/team_10_frontend/assets/102852926/255c8b03-b0bf-4b53-b665-be64467b5d56)
![image](https://github.com/IO2-2023-JB/team_10_frontend/assets/102852926/61615849-4a31-4fd3-848c-b842b80f6f61)

2023-05-18 00:16 UTC, nizioleque requested changes
jest giiiiiit

2023-05-18 00:16 UTC, nizioleque commented on src/pages/Donate/DonateDialog.tsx
> +          error={!isValueValid(+value)}
nie podoba mi się, że error pokazuje się od razu po odpaleniu dialogu - fajniej by było albo po pierwszym "odfokusowaniu" pola (pierwsze `onBlur`) albo dopiero po pierwszym kliknięciu na przycisk 

i według mnie przycisk nie powinien być nigdy disabled, w innych formularzach nigdzie tak nie robimy, ogólnie to gorszy user experience, nie chce mi sie tlumaczyc...

2023-05-18 00:16 UTC, nizioleque commented on src/pages/Donate/DonateDialog.tsx
> +const regex = /^(\d*\.?\d{0,2}|\d+)$/;
jesteśmy Polakami mówimy po polsku, używamy przecinka a nie kropki jako separatora dziesiętnego

to samo przy wyświetlaniu kwot, też trzeba poprawić

2023-05-18 00:16 UTC, nizioleque commented on src/api/donate.ts
> +    },
ten `onSuccess` to nic nie robi w sumie, nie używamy nigdzie takiego klucza

2023-05-18 00:16 UTC, nizioleque commented on src/components/donate/DonateButton.tsx
> +  const [dialogOpen, setDialogOpen] = useState(false);
```suggestion
  const [dialogOpen, setDialogOpen] = useState<boolean>(false);
```

2023-05-18 00:16 UTC, nizioleque commented on src/components/donate/WithdrawButton.tsx
> +  const [dialogOpen, setDialogOpen] = useState(false);
```suggestion
  const [dialogOpen, setDialogOpen] = useState<boolean>(false);
```

2023-05-18 00:16 UTC, nizioleque commented on src/pages/Donate/DonateDialog.tsx
> +    const value = event.target.value;
mało kto tak robi, ale bezpieczniej jest korzystać `currentTarget` niż `target` - `target` to to, co rzeczywiście zostało kliknięte (czyli może to być twój element a może być jakieś jego dziecko), a `currentTarget` to zawsze ten, do którego przypisany został ten listener

2023-05-18 00:16 UTC, nizioleque commented on src/pages/Donate/DonateDialog.tsx
> +  const [value, setValue] = useState('');
```suggestion
  const [value, setValue] = useState<string>('');
```

2023-05-18 00:16 UTC, nizioleque commented on src/pages/Donate/WithdrawDialog.tsx
> +  const [value, setValue] = useState('');
```suggestion
  const [value, setValue] = useState<string>('');
```

2023-05-18 00:16 UTC, nizioleque commented on src/pages/Donate/WithdrawDialog.tsx
> +    const value = event.target.value;
`currentTarget` jak wyżej

2023-05-18 00:16 UTC, nizioleque commented on src/pages/Donate/DonateDialog.tsx
> +          {error?.message}
kiedyś jak ten branch połączy się z branchem z obsługą errorów, trzeba będzie użyć tutaj funkcji `getErrorMessage` którą napisałem na tamtym branchu... na razie zrób tak, bez tego nie będzie się dało zmergować:
```suggestion
          {error?.message} // TODO implement getErrorMessage
```

2023-05-18 00:16 UTC, nizioleque commented on src/pages/Donate/WithdrawDialog.tsx
> +          {error?.message}
```suggestion
          {error?.message} // TODO implement getErrorMessage
```

2023-05-18 00:16 UTC, nizioleque commented on src/pages/User/UserInfo.tsx
> +        <Stack direction='row' spacing={2} sx={{ marginInlineStart: 'auto' }}>
tu zmień spacing na 1 może?

2023-05-19 07:04 UTC, nowakmikolaj commented on src/api/donate.ts
> +    },
prawda, chyba chodziło mi o userKey, wtedy dane uzytkownika ktoremu wplynely pieniadze sie pobiora od nowa nie?

2023-05-19 07:06 UTC, nowakmikolaj commented on src/components/donate/DonateButton.tsx
> +  const [dialogOpen, setDialogOpen] = useState(false);
a dlaczego? to on nie wie automatycznie że to boolean?

2023-05-19 07:08 UTC, nowakmikolaj commented on src/pages/Donate/DonateDialog.tsx
> +          {error?.message}
juz jest

2023-05-19 07:09 UTC, nowakmikolaj commented on src/pages/Donate/DonateDialog.tsx
> +  const [value, setValue] = useState('');
done

2023-05-19 07:09 UTC, nowakmikolaj commented on src/components/donate/WithdrawButton.tsx
> +  const [dialogOpen, setDialogOpen] = useState(false);
done

2023-05-19 07:09 UTC, nowakmikolaj commented on src/pages/Donate/DonateDialog.tsx
> +    const value = event.target.value;
mhm

2023-05-19 07:28 UTC, nowakmikolaj commented on src/pages/Donate/DonateDialog.tsx
> +        <Typography>zł</Typography>
done

2023-05-19 07:40 UTC, nowakmikolaj commented on src/pages/Donate/WithdrawDialog.tsx
> +    const value = event.target.value;
done

2023-05-19 07:40 UTC, nowakmikolaj commented on src/pages/Donate/WithdrawDialog.tsx
> +        <Typography>zł</Typography>
done

2023-05-19 07:40 UTC, nowakmikolaj commented on src/pages/Donate/WithdrawDialog.tsx
> +          {error?.message}
done

2023-05-19 07:40 UTC, nowakmikolaj commented on src/pages/Donate/WithdrawDialog.tsx
> +  const [value, setValue] = useState('');
done

2023-05-19 07:41 UTC, nowakmikolaj commented on src/pages/User/UserInfo.tsx
> +        <Stack direction='row' spacing={2} sx={{ marginInlineStart: 'auto' }}>
done

2023-05-19 07:41 UTC, nowakmikolaj commented on src/pages/User/UserDetails.tsx
> +            <Stack direction='row' spacing={1} sx={{ marginInlineStart: 'auto' }}>
done

2023-05-19 08:51 UTC, nizioleque commented on src/api/donate.ts
> +    },
tak, ale to w ogole nie jest potrzebne, bo user ktory wrzuca donate nigdy nie widzi kwoty (bo nie mozna robic donate sobie samemu). Więc do usunięcia

2023-05-19 08:52 UTC, nizioleque commented on src/components/donate/DonateButton.tsx
> +  const [dialogOpen, setDialogOpen] = useState(false);
wie, ale jak w kodzie gdzieś zrobisz `setDialogOpen('aaaa')` to stwierdzi "aaa, czyli to ma być `boolean | string`? spoko"

2023-05-19 08:54 UTC, nizioleque commented on src/components/donate/DonateButton.tsx
> +  const [dialogOpen, setDialogOpen] = useState(false);
dobra, sprawdziłem i jednak tak nie jest - bierze typ na podstawie domyślnej wartości. Ale jak chcemy np. żeby coś było `string | null` i domyślnie dajemy `null`, to trzeba podać typ, bo nie pozwoli ci przypisać stringa inaczej. Więc jak już trzeba podawać typy, to podajemy wszędzie, taka konwencja

2023-05-19 09:09 UTC, nizioleque commented on src/pages/Donate/WithdrawDialog.tsx
> +      </Stack>
Stack można usunąć

2023-05-19 09:09 UTC, nizioleque approved these changes
popraw te 2 rzeczy i merguj

2023-05-19 09:12 UTC, nowakmikolaj commented on src/components/donate/DonateButton.tsx
> +  const [dialogOpen, setDialogOpen] = useState(false);
ok

2023-05-19 09:27 UTC, merged