Mw 252/date range picker
IO2-2023-JB/team_10_frontend pull request #68
Opened 2023-06-04 22:27 UTC by nowakmikolaj

## Jira task

https://mojewideo.atlassian.net/jira/software/projects/MW/boards/1?selectedIssue=MW-252

## Description

Dodanie walidacji do kontrolek datowych, beginDate nie może być większy niż endDate i odwrotnie

## Added/modified functionality

Kontrolki w filtrach wyszukiwania

## Screenshots

bez zmian wizualnych

2023-06-04 22:27 UTC, nowakmikolaj commented
merge #64 first

2023-06-06 10:21 UTC, nizioleque approved these changes

2023-06-06 12:59 UTC, zagorskim approved these changes

2023-06-07 11:37 UTC, nizioleque requested changes

2023-06-07 11:37 UTC, nizioleque commented on src/pages/Search/DateRangePicker.tsx
> +  const [endDate, setEndDate] = useState<Date | undefined>();
raczej trzymamy się takiej konwencji ze robimy `useState<X | null>(null)` - kiedys ci chyba tlumaczylem roznice miedzy `undefined` a `null`. Ale to nie robi roznicy w sumie wiec nie musisz zmieniac, tak na przyszlosc

2023-06-07 11:37 UTC, nizioleque commented on src/pages/Search/DatePickerFilter.tsx
> +function DatePickerFilter({
kliknięcie "Wyczyść" nie czyści "Dodano przed"

2023-06-07 11:37 UTC, nizioleque commented on src/pages/Search/DateRangePicker.tsx
> +  const [beginDate, setBeginDate] = useState<Date | undefined>();
coś tu nie śmiga - jak najpierw ustawię "dodano przed" na 5 czerwca, to potem dalej mogę ustawić "dodano po" na późniejszą datę

2023-06-07 11:37 UTC, nizioleque commented on src/pages/Search/DateRangePicker.tsx
> +  const [beginDate, setBeginDate] = useState<Date | undefined>();
tak ma być?

2023-06-07 11:37 UTC, nizioleque commented on src/pages/Search/DateRangePicker.tsx
> +  const [beginDate, setBeginDate] = useState<Date | undefined>();
dobra chyba magicznie sie naprawilo, ale sprawdz to jeszcze u siebie

2023-06-07 11:37 UTC, nizioleque commented on src/pages/Search/DatePickerFilter.tsx
> +function DatePickerFilter({
albo jednak dziala, wez zobacz

2023-06-07 11:37 UTC, nizioleque commented on src/pages/Search/DatePickerFilter.tsx
> +      format='dd-MM-yyyy'
w polsce raczej używamy kropek a nie myślników do daty

2023-06-07 11:38 UTC, nizioleque requested changes
.

2023-06-08 11:32 UTC, nowakmikolaj commented on src/pages/Search/DatePickerFilter.tsx
> +      format='dd-MM-yyyy'
słusznie

2023-06-08 11:41 UTC, nowakmikolaj commented on src/pages/Search/DateRangePicker.tsx
> +  const [endDate, setEndDate] = useState<Date | undefined>();
racja

2023-06-14 18:03 UTC, nizioleque approved these changes

2023-06-14 19:42 UTC, merged