Mw 245/snackbars
IO2-2023-JB/team_10_frontend pull request #72
Opened 2023-06-05 19:44 UTC by nowakmikolaj

## Jira task

[insert Jira task URL]

## Description

[provide short description]

## Added/modified functionality

- [item 1]

## Screenshots

[paste screenshots]

2023-06-07 12:05 UTC, nizioleque requested changes

2023-06-08 13:34 UTC, nowakmikolaj commented on src/components/StatusSnackbar.tsx
> +  const [isOpen, setOpen] = useState<boolean>(false);
ok

2023-06-08 13:59 UTC, nowakmikolaj commented on src/pages/Playlist/PlaylistDelete.tsx
> +      navigate(`${ROUTES.USER}/${playlist.authorId}/playlists`);
done

2023-06-08 14:14 UTC, nowakmikolaj commented on src/pages/Video/VideoDelete.tsx
>        if (!asMenuItem) navigate(`${ROUTES.USER}/${loggedUserDetails?.id}`);
1. poprawione
2. ale faktycznie cos nie dziala, ten navigate(-1) tutaj nie działa XD nie wiem czemu, dla usuwania playlist działa

2023-06-08 14:21 UTC, nowakmikolaj commented on src/components/StatusSnackbar.tsx
> +function StatusSnackbar({ severity = 'success' }: StatusSnackbarProps) {
done, ustawiam recoil value na null przy wylogowywaniu

2023-06-14 22:24 UTC, nizioleque approved these changes

2023-06-15 16:46 UTC, merged