WIP Mw 241/ticket page
IO2-2023-JB/team_10_frontend pull request #74
Opened 2023-06-07 16:15 UTC by zagorskim

## Jira task

https://mojewideo.atlassian.net/jira/software/projects/MW/boards/1?selectedIssue=MW-241

## Description

Ticket list offering functionalities for admin and normal user

## Added/modified functionality

- jakaś strona z listą ticketów i statusem

- user moze wyswietlac swoje tickety

- admin moze dodatkowo odpowiadac

- potencjalnie uzycie komentarzy

- fajnie jakby od ticketu dalo sie przejsc linkiem do contentu zglaszanego

- user może edytować własny ticket (na który jeszcze nie odpowiedziano?)

## Screenshots

![image](https://github.com/IO2-2023-JB/team_10_frontend/assets/84161388/45c9632c-df6f-4a8b-a5a9-cdd422ae1481)
![image](https://github.com/IO2-2023-JB/team_10_frontend/assets/84161388/afb1cc4a-a2ce-4288-b8e9-aa876856e098)

2023-06-15 16:56 UTC, nizioleque requested changes

2023-06-15 16:56 UTC, nizioleque commented on src/components/TicketButton.tsx
> +function TicketButton({
może lepiej zrobić jakiś komponent bazowy który renderuje różnego buttona w zależności od ButtonType i od niego dwa pochodne, jeden do zgłaszania drugi do odpowiadania

2023-06-15 16:56 UTC, nizioleque commented on src/api/ticket.ts
> +}
tak jak napisałem wcześniej (w `TicketButton`), to powinny być dwa oddzielne hooki w dwóch oddzielnych komponentach

2023-06-15 16:56 UTC, nizioleque commented on src/api/ticket.ts
> +    queryKey: [ticketKey, loggedInUser?.id],
nie rozumiem po co ten loggedInUser tutaj, zawsze pobieramy tę samą listę ticketów nie? nie potrzeba ich rozróżniać po kluczach

2023-06-15 16:56 UTC, nizioleque commented on src/utils/utils.ts
> +      return '';
to się nigdy nie wywoła, martwy kod

2023-06-15 16:56 UTC, nizioleque commented on src/utils/utils.ts
> +      return '';
jak niżej

2023-06-15 16:56 UTC, nizioleque commented on src/components/TicketButton.tsx
> +  return (
aktualnie admin moze zglaszac (np. wszedlem na innego usera i mam tne przycisk) -- proponuje zrobic tu `return null` jesli sie jest adminem

2023-06-15 16:56 UTC, nizioleque commented on src/pages/Video/Metadata.tsx
> +          )}
w UI telefonowym ten przycisk ma wiekszy padding niz pozostale

2023-06-15 16:56 UTC, nizioleque commented on src/pages/Ticket/TicketList.tsx
> +          key={index}
w sumie to możesz użyć `ticket.targetId`, nie?

2023-06-15 16:56 UTC, nizioleque commented on src/pages/Ticket/TicketListItem.tsx
> +  //if (isCommentDeleted) isCommentLoading = isCommentResponseLoading = false;
usun to

usun to

usun 

usun 

usun usun toooo

2023-06-15 16:56 UTC, nizioleque commented on src/pages/Ticket/TicketListItem.tsx
> +      {isChildComponentDataLoading && (
możesz `? :` zamiast takich dwóch klocków z `&&`

2023-06-15 16:56 UTC, nizioleque commented on src/pages/Ticket/TicketListItem.tsx
> +  );
tego chyba nie trzeba pobierac jak nie jestes adminem

2023-06-15 16:56 UTC, nizioleque commented on src/pages/Ticket/TicketListItem.tsx
> +
o co chodzi, backend nie powinien 404 zwracac jak komentarz nie istnieje?

2023-06-15 16:56 UTC, nizioleque commented on src/pages/Ticket/TicketListItem.tsx
> +function TicketListItem({ ticket, isAdmin }: TicketListItemProps) {
wielkie bydle żeś zrobił, byłoby w chuj czytelniej jakbyś chociażby ten podgląd zgłaszanego elementu przeniósł do oddzielnego komponentu, bo ma dosyc skomplikowana logike

2023-06-15 16:56 UTC, nizioleque commented on src/pages/Ticket/TicketListItem.tsx
> +      : false;
XDD serio?

2023-06-15 16:56 UTC, nizioleque commented on src/pages/Ticket/TicketListItem.tsx
> +  );
a nie mozesz po prostu raz tego hooka wywołać? 

```suggestion
  const isComment = [TicketTargetType.Comment, TicketTargetType.CommentResponse].includes(ticket.targetType);

  const {
    data: commentDetails,
    isLoading: isCommentDetailsLoading,
    error: commentError,
  } = useCommentById(
    isComment ? ticket.targetId : undefined
  );
```

2023-06-15 16:56 UTC, nizioleque commented on src/pages/Ticket/TicketListItem.tsx
> +  const [expanded, setExpanded] = useState<boolean>(false);
jak masz ochotę to możesz użyć `useToggle` z `usehooks-ts`, wczoraj się zachwyciłem jak to znalazłem XD

2023-06-15 16:56 UTC, nizioleque commented on src/pages/Ticket/TicketListItem.tsx
> +              {submitterDetails && <UserInfo userDetails={submitterDetails} isSelf />}
tu tez by mogl byc jakis skeleton bo przeskakuje

2023-06-15 16:56 UTC, nizioleque commented on src/pages/Ticket/TicketListItem.tsx
> +              {submitterDetails && <UserInfo userDetails={submitterDetails} isSelf />}
w ogóle w UserInfo już jest skeleton zaimplementowany, mozesz to renderowac zawsze (nie-warunkowo) i bedzie git

2023-06-15 16:56 UTC, nizioleque commented on src/pages/Ticket/TicketListItem.tsx
> +                isResponse={commentDetails !== null ? false : true}
```suggestion
                isResponse={commentDetails === null}
```

2023-06-15 17:24 UTC, zagorskim commented on src/pages/Ticket/TicketListItem.tsx
> +      : false;
XDD

2023-06-15 18:32 UTC, zagorskim commented on src/components/NavBar/NavBar.tsx
> +
S7 dodajmy ok? średnio dzisiaj z czasem stoję

2023-06-15 18:34 UTC, zagorskim commented on src/components/TicketButton.tsx
> +        {(isResponse ? 'Rozwiąż ' : 'Zgłoś ') + targetNameInTitle}
chciałem to tak zrobić, ale zamiast backticków dawałem zwykłe apostrofy i mi nie dzialalo xdd

zmieniłem

2023-06-15 18:42 UTC, zagorskim commented on src/components/TicketButton.tsx
> +function TicketButton({
S7?

2023-06-15 18:51 UTC, zagorskim commented on src/components/TicketButton.tsx
> +  return (
done

2023-06-15 18:53 UTC, zagorskim commented on src/components/TicketButton.tsx
> +            color: targetNameInTitle === 'komentarz' ? 'grey.800' : 'primary.main',
I tak będzie do zmiany przy wydzialeniu z tego dwóch oddzielnych komponentów, więc dodaję do taska na s7

2023-06-15 18:54 UTC, zagorskim commented on src/components/TicketButton.tsx
> +                : undefined
s7

2023-06-15 19:06 UTC, zagorskim commented on src/components/video/VideoListItemMenu.tsx
> +        )}
mi się pokazuje xd

może byłeś zalogowany jako admin?

2023-06-15 19:16 UTC, zagorskim commented on src/pages/Ticket/TicketListItem.tsx
> +      {isChildComponentDataLoading && (
jest jakiś case, w którym ten if nie działa i jestem przewrażliwiony xd

2023-06-15 19:28 UTC, zagorskim commented on src/pages/Ticket/TicketListItem.tsx
> +  //if (isCommentDeleted) isCommentLoading = isCommentResponseLoading = false;
czemu linter nie powiedział ;oooo

2023-06-15 19:42 UTC, zagorskim commented on src/utils/utils.ts
> +      return '';
na zajęciach uczyli zawsze dawać default.....

2023-06-15 19:44 UTC, zagorskim commented on src/pages/Ticket/TicketListItem.tsx
> +              {submitterDetails && <UserInfo userDetails={submitterDetails} isSelf />}
rozwiązane na telegramie

2023-06-15 19:49 UTC, zagorskim commented on src/pages/Ticket/TicketListItem.tsx
> +  const [expanded, setExpanded] = useState<boolean>(false);
S7, do zmiany tutaj i w paru innych komponentach pewnie

2023-06-15 19:56 UTC, zagorskim commented on src/pages/Ticket/TicketListItem.tsx
> +  );
a mogę

2023-06-15 20:05 UTC, zagorskim commented on src/pages/Ticket/TicketListItem.tsx
> +function TicketListItem({ ticket, isAdmin }: TicketListItemProps) {
rozbiję to ładniej na S7, obiecuję

2023-06-15 20:11 UTC, zagorskim commented on src/pages/Ticket/TicketListItem.tsx
> +
powinien, ale miałem message 404 i dostałem mindfucka, potem zapomniałem o problemie xddd

2023-06-15 20:17 UTC, zagorskim commented on src/pages/User/UserInfoButtons.tsx
> +          targetNameInTitle='konto'
done

2023-06-15 20:28 UTC, zagorskim commented on src/pages/Video/Metadata.tsx
> +          )}
done

2023-06-15 21:22 UTC, zagorskim commented on src/pages/Ticket/TicketListItem.tsx
> +  );
jednak nie

2023-06-15 22:45 UTC, nizioleque approved these changes

2023-06-15 22:45 UTC, nizioleque commented on src/components/video/VideoListItemMenu.tsx
> +  const showMenu = Boolean(!isAuthor || playlistId);
no to teraz mistrzu jak wejdziesz na wlasny profil to ci sie nie pokaze menu przy filmach

2023-06-15 22:45 UTC, nizioleque commented on src/components/video/VideoListItemMenu.tsx
> +  const showMenu = Boolean(!isAuthor || playlistId);
jesli dobrze widze to zawsze ma sie pokazywac to menu teraz, czyli usun ten warunek wgl i L29

2023-06-15 22:45 UTC, nizioleque commented on src/api/ticket.ts
> +}
to zrob taska

2023-06-15 22:45 UTC, nizioleque commented on src/components/NavBar/NavBar.tsx
> +
to zrob taska

2023-06-15 22:45 UTC, nizioleque commented on src/components/TicketButton.tsx
> +function TicketButton({
to zrob taska

2023-06-15 22:45 UTC, nizioleque commented on src/components/TicketButton.tsx
> +                : undefined
to zrob taska

2023-06-15 22:45 UTC, nizioleque commented on src/components/TicketButton.tsx
> +        {`${isResponse ? 'Rozwiąż' : 'Zgłoś'} ${targetNameInTitle}`}
ten sam string 3 razy jest, juz pisalem o tym

2023-06-15 22:45 UTC, nizioleque commented on src/pages/Ticket/TicketListItem.tsx
> +  const [expanded, setExpanded] = useState<boolean>(false);
nie no, olej to

2023-06-15 22:45 UTC, nizioleque commented on src/components/TicketButton.tsx
> +            padding: isMobile ? '5px' : undefined,
zamiast tak na pałę robić to mogłeś po prostu spojrzeć jak ja to zrobiłem w `AddToPlaylist`

```
          size={isMobile ? 'small' : 'medium'}
```

2023-06-15 22:45 UTC, nizioleque commented on src/pages/Ticket/TicketListItem.tsx
> +  const isChildComponentDataLoading = isCommentLoading || isCommentResponseLoading;
```suggestion
  const dupa = useCommentById(
    ticket.targetType === TicketTargetType.Comment ? ticket.targetId : undefined
  );

  const chuj = useCommentResponseById(
    ticket.targetType === TicketTargetType.CommentResponse ? ticket.targetId : undefined
  );

  const handleExpandClick = () => {
    setExpanded(!expanded);
  };

  const link =
    ticket.targetType === TicketTargetType.Video
      ? `${ROUTES.VIDEO}/${ticket.targetId}`
      : ticket.targetType === TicketTargetType.User
      ? `${ROUTES.USER}/${ticket.targetId}`
      : ticket.targetType === TicketTargetType.Playlist
      ? `${ROUTES.PLAYLIST}/${ticket.targetId}`
      : undefined;

 const cipa =
 ticket.targetType === TicketTargetType.Comment ? dupa
 : ticket.targetType === TicketTargetType.CommentResponse ? chuj
 : undefined;

  const isCommentDeleted =
    cipa?.error?.response?.status === 404;

  const isChildComponentDataLoading = cipa?.isLoading ?? false;
```

2023-06-15 22:45 UTC, nizioleque commented on src/pages/Ticket/TicketListItem.tsx
> +  const isChildComponentDataLoading = isCommentLoading || isCommentResponseLoading;
to jest ta dyskusja co kiedys mielismy

2023-06-15 22:45 UTC, nizioleque commented on src/pages/Ticket/TicketListItem.tsx
> +  const isChildComponentDataLoading = isCommentLoading || isCommentResponseLoading;
ale juz olej to

2023-06-15 22:46 UTC, nizioleque commented on src/utils/utils.ts
> +      return '';
jakby byl jakis przypadek nieobsluzony to eslint chyba by plakal ze funkcja moze zwrocic undefined mimo ze ma zwrocic string

2023-06-15 22:47 UTC, nizioleque commented on src/pages/Ticket/TicketListItem.tsx
> +      {isChildComponentDataLoading && (
nie no gosciu niemozliwe

2023-06-15 23:20 UTC, zagorskim commented on src/pages/Ticket/TicketListItem.tsx
> +  const isChildComponentDataLoading = isCommentLoading || isCommentResponseLoading;
dam na te s7, bo Mikołaj chce to zmergowane

2023-06-15 23:37 UTC, zagorskim commented on src/components/TicketButton.tsx
> +            padding: isMobile ? '5px' : undefined,
nic to nie zmienia

2023-06-15 23:44 UTC, zagorskim commented on src/components/TicketButton.tsx
> +        {`${isResponse ? 'Rozwiąż' : 'Zgłoś'} ${targetNameInTitle}`}
done, sorka

2023-06-16 00:36 UTC, nowakmikolaj approved these changes

2023-06-16 00:36 UTC, merged