WIP Mw 257/papiesz mode
IO2-2023-JB/team_10_frontend pull request #75
Opened 2023-06-10 01:00 UTC by zagorskim

## Jira task

https://mojewideo.atlassian.net/jira/software/projects/MW/boards/1?selectedIssue=MW-257

## Description

Aplikacja dostraja się do aktualnej pory dnia.

## Added/modified functionality

- ulubiona piosenka w tle
- odpowiednie barwy na odpowiednie pory dnia

## Screenshots

![image](https://github.com/IO2-2023-JB/team_10_frontend/assets/84161388/ff183634-b90a-4ac3-8880-df6085d68374)

2023-06-14 22:58 UTC, nizioleque requested changes

2023-06-14 22:58 UTC, nizioleque commented on src/components/layout/AppLoader.tsx
> +  }, [setAppMode]);
używanie `setInterval` to nie taka prosta sprawa, bo trzeba jeszcze usunąć ten interval jak komponent się usuwa, proponuję użyć hooka `useInterval` z biblioteki `usehooks-ts`, którą mamy już w projekcie

https://usehooks-ts.com/react-hook/use-interval

2023-06-14 22:58 UTC, nizioleque commented on src/components/layout/AppLoader.tsx
> +      const now = new Date(Date.now());
z tego co wiem to wystarczy 

albo `new Date()`

albo `Date.now()`

2023-06-14 22:58 UTC, nizioleque commented on src/components/layout/AppLoader.tsx
> +    }, MODE_DURATION);
według mnie to sprawdzenie powinno być dużo częściej, np co sekundę, żeby zawsze się odpalało najpóźniej o 21:37:01. Jak sprawdzasz co minutę, to może się odpalić o 21:37:59

2023-06-14 22:58 UTC, nizioleque commented on src/theme.ts
> +export const getTheme = (appMode: AppMode) => ({
skoro na dole jest `export default` to to nie jest potrzebne

2023-06-14 22:58 UTC, nizioleque commented on src/theme.ts
> +    mode: 'dark' as PaletteMode,
a to po co?

2023-06-14 23:29 UTC, zagorskim commented on src/components/layout/AppLoader.tsx
> +      const now = new Date(Date.now());
tylko pierwsze zadziała jak coś

2023-06-14 23:30 UTC, zagorskim commented on src/components/layout/AppLoader.tsx
> +    }, MODE_DURATION);
stwierdziłem, że bez znaczenia o której, a bałem się trochę robić to często ze względu na performance

ale pewnie racja, bez znaczenia chyba, bo tych obliczeń jest mało

2023-06-15 00:03 UTC, zagorskim commented on src/components/layout/AppLoader.tsx
> +  }, [setAppMode]);
done

2023-06-15 00:04 UTC, zagorskim commented on src/theme.ts
> +    mode: 'dark' as PaletteMode,
Po zmianie na funkcję zaczęło tu krzyczeć, że typy się nie zgadzają, ale teraz usuwam i działa - idk

2023-06-15 00:07 UTC, zagorskim commented on src/theme.ts
> +    mode: 'dark' as PaletteMode,
a jednak linter to znajduje: 
![image](https://github.com/IO2-2023-JB/team_10_frontend/assets/84161388/f9ecf271-d5c4-438f-ae04-652b7dd4aeeb)

2023-06-15 11:50 UTC, nizioleque approved these changes
popraw to jedno i merge

2023-06-15 16:23 UTC, zagorskim commented on src/components/layout/AppLoader.tsx
> +      audioRef.current?.play();
done ofc

2023-06-15 17:35 UTC, nizioleque approved these changes
zajebiste

2023-06-15 17:56 UTC, merged